server:
  port: 8080
spring:
  application:
    name: test

  # Database connection properties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easyLearning?createDatabaseIfNotExist=true
    username: root
    password:

  # Hibernate properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect




jwt:
  signerKey: "a0YJZqjYV1ny1WVzrErLD1cWFmSiTfzDOIhsYH+Fw45JDN6WukcgWRWd+4zka+9G"
  valid-duration: 36000  # in seconds
  refreshable-duration: 36000  # in seconds

