server:
  port: 8080
spring:
  application:
    name: test

  # Database connection properties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easyLearning?createDatabaseIfNotExist=true
    username: root
    password:
    #password: Password@1234

  # Hibernate properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: workflowttp@gmail.com
    password: mytk qdlt eyfl xfby
    fromEmail: workflowttp@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

outbound:
  identity:
    client-id: "409126728225-mn4h754gh3l2a1vhd3jjk74ug5b0dmug.apps.googleusercontent.com"
    client-secret: "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"
    redirect-uri: ""

jwt:
  signerKey: "a0YJZqjYV1ny1WVzrErLD1cWFmSiTfzDOIhsYH+Fw45JDN6WukcgWRWd+4zka+9G"
  valid-duration: 36000  # in seconds
  refreshable-duration: 36000  # in seconds

feign:
  client:
    config:
      default:
        loggerLevel: full  # Ghi log đầy đủ các request/response của Feign
        connectTimeout: 5000  # Thời gian timeout kết nối (5 giây)
        readTimeout: 5000  # Thời gian timeout đọc dữ liệu (5 giây)


